name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build and run client
      run: yarn && yarn start &
      working-directory: ./client
      env: 
        BROWSER: none
    - name: build and run server
      run: yarn && yarn start:dev &
      working-directory: ./server
    - name: run tests
      run: |
        yarn wait-port localhost:3000 &&
        yarn wait-port localhost:4000 &&
        yarn test:nightwatch
      working-directory: ./client
      env:
        BROWSER: chrome
