name: Node CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        BROWSER: [chrome, firefox]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn client
      run: yarn
      working-directory: ./client
    - name: run client
      run: yarn start &
      working-directory: ./client
      env:
        BROWSER: none
    - name: yarn server
      run: yarn
      working-directory: ./server
    - name: run server
      run: yarn start:dev &
      working-directory: ./server
    - name: wait for services
      run: yarn wait-port localhost:3000 && yarn wait-port localhost:4000
      working-directory: ./client
    - name: run tests
      run: yarn test:nightwatch --headless
      working-directory: ./client
