name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build and start client
      run: |
        cd client
        yarn
        yarn start
    - name: build and start server
      run: |
        cd ../server
        yarn
        yarn start:dev
    - name: browser test
      run: |        
        cd ../client
        yarn start && yarn nightwatch                
      env:
        CI: true
        BROWSER: chrome
